"""Them bang user template

Revision ID: 3c7cb0d20fa8
Revises: 9e35c9fe2f0f
Create Date: 2026-07-28 13:45:48.802636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c7cb0d20fa8'
down_revision: Union[str, None] = '9e35c9fe2f0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
