"""Them 2 cot cho shortlist

Revision ID: 9e35c9fe2f0f
Revises: b5d2e8a1c4f7
Create Date: 2026-07-28 13:19:45.160860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e35c9fe2f0f'
down_revision: Union[str, None] = 'b5d2e8a1c4f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shortlist_items', sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('shortlist_items', sa.Column('notified_status', sa.String(length=50), nullable=True))
    op.drop_column('users', 'verify_token_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verify_token_version', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_column('shortlist_items', 'notified_status')
    op.drop_column('shortlist_items', 'notified_at')
    # ### end Alembic commands ###
