"""them_bang_phong_van_va_cau_hoi

Revision ID: ea8ae8cda1d3
Revises: e2b3c4d5f6a7
Create Date: 2026-07-06 13:16:12.695318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea8ae8cda1d3'
down_revision: Union[str, None] = 'e2b3c4d5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_questions', sa.Column('expected_answer', sa.Text(), nullable=True))
    op.add_column('interview_questions', sa.Column('answer_text', sa.Text(), nullable=True))
    op.add_column('interview_questions', sa.Column('ai_evaluation', sa.Text(), nullable=True))
    op.add_column('interview_questions', sa.Column('score', sa.Float(), nullable=True))
    op.add_column('interview_questions', sa.Column('is_ai_generated', sa.Boolean(), nullable=False))
    op.add_column('interview_questions', sa.Column('order_index', sa.Integer(), nullable=False))
    op.add_column('interviews', sa.Column('status', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'status')
    op.drop_column('interview_questions', 'order_index')
    op.drop_column('interview_questions', 'is_ai_generated')
    op.drop_column('interview_questions', 'score')
    op.drop_column('interview_questions', 'ai_evaluation')
    op.drop_column('interview_questions', 'answer_text')
    op.drop_column('interview_questions', 'expected_answer')
    # ### end Alembic commands ###
